baseurl = "https://bybeet.github.com/"
title = "Cold Espresso"
author = "Travis Bybee"
canonifyurls = true
languagecode = "en"
theme = "hugo-black-and-light-theme"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Cold Espresso"

[[menu.main]]
    name = "Projects"
    url  = "https://github.com/bybeet"
[[menu.main]]
    name = "Photography"
    url  = "http://travisbybee.com"
